src/PushNinja/Controllers/AppsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PushNinja.Models;
using System.IO;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;

namespace PushNinja.Controllers
{
    [Authorize]
    public class AppsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Apps/
        public async Task<ActionResult> Index()
        {
            var apps = db.Apps;
            return View(await apps.ToListAsync());
        }

        // GET: /Apps/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Apps/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,AppleCertificatePassword,GcmAuthorizationToken")] App app, HttpPostedFileBase appleCertificate)
        {
            if (ModelState.IsValid)
            {
                app.UserId = User.Identity.GetUserId();
                app.AppToken = Convert.ToBase64String(Guid.NewGuid().ToByteArray());

                if (appleCertificate != null)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        appleCertificate.InputStream.CopyTo(memoryStream);
                        app.AppleCertificate = memoryStream.ToArray();
                    }
                }

                db.Apps.Add(app);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(app);
        }

        // GET: /Apps/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            App app = await db.Apps.FindAsync(id);
            if (app == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.Users, "Id", "UserName", app.UserId);
            return View(app);
        }

        // POST: /Apps/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,AppleCertificatePassword,GcmAuthorizationToken")] App app, HttpPostedFileBase appleCertificate)
        {
            if (ModelState.IsValid)
            {
                var dbApp = db.Apps.SingleOrDefault(p => p.Id == app.Id);
                dbApp.Name = app.Name;
                dbApp.GcmAuthorizationToken = app.GcmAuthorizationToken;
                dbApp.AppleCertificatePassword = app.AppleCertificatePassword;

                if (appleCertificate != null)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        appleCertificate.InputStream.CopyTo(memoryStream);
                        dbApp.AppleCertificate = memoryStream.ToArray();
                    }
                }

                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(app);
        }

        // GET: /Apps/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            App app = await db.Apps.FindAsync(id);
            if (app == null)
            {
                return HttpNotFound();
            }
            return View(app);
        }

        // POST: /Apps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            App app = await db.Apps.FindAsync(id);
            db.Apps.Remove(app);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/PushNinja/Views/Apps/Create.cshtml
@model PushNinja.Models.App

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Apps", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>App</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AppleCertificate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="AppleCertificate" />
                @Html.ValidationMessageFor(model => model.AppleCertificate)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.AppleCertificatePassword, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AppleCertificatePassword)
                @Html.ValidationMessageFor(model => model.AppleCertificatePassword)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.GcmAuthorizationToken, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GcmAuthorizationToken)
                @Html.ValidationMessageFor(model => model.GcmAuthorizationToken)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/PushNinja/Views/Apps/Delete.cshtml
@model PushNinja.Models.App

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>App</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

src/PushNinja/Views/Apps/Edit.cshtml
@model PushNinja.Models.App

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Apps", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>App</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AppleCertificate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="appleCertificate" />
                @Html.ValidationMessageFor(model => model.AppleCertificate)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.AppleCertificatePassword, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AppleCertificatePassword)
                @Html.ValidationMessageFor(model => model.AppleCertificatePassword)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.GcmAuthorizationToken, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GcmAuthorizationToken)
                @Html.ValidationMessageFor(model => model.GcmAuthorizationToken)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/PushNinja/Views/Apps/Index.cshtml
@model IEnumerable<PushNinja.Models.App>

@{
    ViewBag.Title = "Apps";
}

<h2>Apps</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AppToken)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Name, "Edit", new { id = item.Id })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AppToken)
        </td>
        <td>
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>